language: node_js
node_js:
  - "node"
branches:
  only:
  - master
install:
  - npm install -g firebase-tools
  - npm install -g typescript
  - cd functions
  - npm install
  - tsc
  - cd ..
script:
  - firebase use default --token $FIREBASE_DEPLOY_KEY

  - firebase functions:config:set slack.id=$SLACK_ID --token $FIREBASE_DEPLOY_KEY
  - firebase functions:config:set slack.secret=$SLACK_SECRET --token $FIREBASE_DEPLOY_KEY

  - firebase deploy -m "Travis build $TRAVIS_BUILD_NUMBER" --non-interactive --token $FIREBASE_DEPLOY_KEY